# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alojamento da Rua da Fonte
person: João Encarnação
email: j_encarnacao@yahoo.com
telephone: 962 801 954
description: > # this means to ignore newlines until "baseurl:"
  Description.
baseurl: "/zh" # the subpath of your site, e.g. /blog
url: "http://jgte.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
